### ISSUE TITLE
[Feature Request] Include "Expert Picture Settings" if possible

### ISSUE THREAD

**Issue by digital-mystik** [wseemann/RoMote#11]
Not sure how Roku implements the "Expert Picture Settings" in their application, but it would be a nice feature to include if it isn't proprietary or too difficult.

**Comment by wseemann** [comment]
Hi @digital-mystik, unfortunately, Roku doesn't offer a way to mimic the "Expert Picture Settings" via their SDK. Therefore, I won't be able to implement this feature.
