### ISSUE TITLE
Cannot power on TV

### ISSUE THREAD

**Issue by oxr463** [wseemann/RoMote#13]
Is it even possible?

**Comment by srwareham** [comment]
Assuming you have a roku TV, you can enable the "Fast TV start" setting under power settings. Should let you turn the TV on with the RoMote. That said, this will increase the idle power usage of your TV.

**Comment by Skylead** [comment]
Did this stop working for anyone else this week? Using TCL TV. Seems like maybe Roku changed the power button api since power off is no longer working either.

**Comment by hisb1** [comment]
@Skylead yes, same here. Cannot power on (from quick start) or off since a couple weeks ago.

**Comment by Epicanis** [comment]
I _used_ to be able to power my RokuTV on and off with this app, but it no longer seems to have any effect. (With the tactile feedback turned on I can tell the interface recognizes I've pushed the power button, but I no longer get the "are you sure you want to turn this thing off" message that I would swear used to come up, and the TV ignores me.)
I've noticed no other issues, only the power on/off seems to have stopped working.
I haven't yet had a chance to go digging and see if the Roku API or this app is what's changed.

**Comment by wseemann** [comment]
Please ensure you are running version [1.0.17](https://github.com/wseemann/RoMote/releases/download/v1.0.17/RoMote-1.0.17.apk). Version 1.0.16 had a bug that broke the power button. If the problem persists please report back here.

**Comment by Epicanis** [comment]
Oh, thank you - it appears f-droid is still stuck on 1.0.16. Hopefully they'll get that updated sometime soon and I can give it a try.

**Comment by Skylead** [comment]
Can confirm that 1.0.17 fixes this issue, what is causing F-Droid to not update? I thought they built weekly

**Comment by e-t-l** [comment]
> Can confirm that 1.0.17 fixes this issue, what is causing F-Droid to not update? I thought they built weekly

Following up on this, anyone know when F-droid will update to 1.0.21? I tried downloading the apk directly from github but it just says "app not installed" (I sideload apps all the time so it's not a permissions issue).

**Comment by wseemann** [comment]
@e-t-l You're probably receiving the "app not installed" if you have the F-Droid version installed because my APK is signed with a different key (they use their own key when building from source). I have no control over. when they update the app on their side. There was a versioning issue that prevented their build server from building my code, but I resolved that over a month ago. I'd suggest filing a ticket with them to get things moving.
