### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [wseemann/RoMote#17]
So tag v1.0.1**8** builds versionCode 1**8** and versionName 1.0.1**7** ? But versionName decides `commit` in F-Droid metadata hence on [autoupdate](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/wseemann.media.romote.yml#L149) F-Droid [tries to build](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/wseemann.media.romote.yml#L135) `v1.0.17` instead :(

Ref: https://f-droid.org/wiki/index.php?title=wseemann.media.romote/lastbuild_18&oldid=274673

**Comment by wseemann** [comment]
@licaon-kter Thanks for creating this issue. I've read you comment several times over and I'm still a little confused as to what I need to do on my end to correct this. Do I simply need to release a new version and update the `versionCode` to 19 and `versionName` to 1.0.18? I'd really like to see this get updated in f-droid so I'm willing to help in any way that I can.

**Comment by licaon-kter** [comment]
Commit name and versionName should match, we don't care about versionCode.

**Comment by Pentaphon** [comment]
@wseemann see here. 

https://gitlab.com/fdroid/fdroiddata/-/issues/2218

**Comment by wseemann** [comment]
This should be fixed in the latest release (tag v1.0.20).
