### ISSUE TITLE
How is this different from official Roku remote app? 

### ISSUE THREAD

**Issue by e-t-l** [wseemann/RoMote#18]
How is this (or any of the dozen other closed-source Roku remote apps available on the Play Store, for that matter) different than the official Roku Remote android app?

**Comment by wseemann** [comment]
As you noted in your question, all the other apps in the market are closed source and/or ad supported. Mine is fully open source and does not contain ads or usage tracking. There are plenty of people that would rather use an open source version of an application than an equivalent closed source version. Beyond that, my app has a much lower storage and memory footprint and is the only app in the market, besides the official Roku app, that supports private listening.

**Comment by as2814** [comment]
Thanks for the app makes life easier for roku usera. Quick question: Do you have the ability to mirror screen images and video? If yes how does it work here? I know we can do that with the official app.

**Comment by sunilkv** [comment]
Hi

**Comment by wseemann** [comment]
Hey, what did you need?

**Comment by redchilis** [comment]
> As you noted in your question, all the other apps in the market are closed source and/or ad supported. Mine is fully open source and does not contain ads or usage tracking. There are plenty of people that would rather use an open source version of an application than an equivalent closed source version. Beyond that, my app has a much lower storage and memory footprint and is the only app in the market, besides the official Roku app, that supports private listening.

Hi,
Does private listening use and Google Play Services?
I use LineageOS without Gapps.
Will the official Roku Remote or your open-source one work without Gapps or will it need atleast microG.
Thanks

**Comment by wseemann** [comment]
@as2814 The cast feature isn't a publicly documented protocol and no API exists for it. RoMote does not support casting to a Roku device currently.
