### ISSUE TITLE
Cannot install on Android 12

### ISSUE THREAD

**Issue by m-boyd** [wseemann/RoMote#24]
F-Droid is suggesting that the SDK is lower than the Android 12 SDK.

![Screenshot_20211021-074609](https://user-images.githubusercontent.com/454858/138271946-4c5fe201-2a2a-42a4-b5a1-778c676e4378.png)

**Comment by m-boyd** [comment]
Thanks for explaining this. I tried installing your most recent APK from releases but received a "problem parsing the package" message. Any ideas?

**Comment by paulv** [comment]
I was able to install that one without any problems.

Thanks!
