### ISSUE TITLE
Not working very well since Android 12

### ISSUE THREAD

**Issue by chriscrutch** [wseemann/RoMote#28]
I've been using the app on my Android phone for quite some time, usually using it with the widget on my home screen. I recently got the Android 12 update, and ever since then the remote widget does not work. If I open the full app and choose the "remote" portion of it, I can make exactly one click on the remote before the app crashes and force closes. 

The official Roku Remote app's widget is also not working for me. I don't know if it's also since the Android 12 update or if it's coincidental, I only downloaded the official app to test it after I found RoMote wasn't working any more. 

I tried allowing RoMote to have unrestricted battery usage too, thinking maybe the battery optimization was doing something new, but that doesn't seem to have helped at all.

**Comment by pupitetris** [comment]
I am using the official, Play Store version of RoMote on an Android 14 phone and it is working just fine. Is it still giving you trouble?

**Comment by chriscrutch** [comment]
> Is it still giving you trouble?

This post was three years ago. It's not giving me any trouble because I stopped using it long ago. Lol.

**Comment by pupitetris** [comment]
Ah, OK. So, you haven't tried any new versions since. If you are still using Roku devices, maybe it would be worth to try the application again, as the problem may have been solved.
