### ISSUE TITLE
Widget not working

### ISSUE THREAD

**Issue by hobgoblina** [wseemann/RoMote#30]
The controls are working fine for me from inside the app, but none of the widget buttons are doing anything. Not working on either Pixel 4a 5g nor Galaxy Tab S8+. Both running Android 12.

**Comment by wseemann** [comment]
This should be resolved in version [version 1.0.26](https://github.com/wseemann/RoMote/releases/tag/v1.0.26). Please test using this version and feel free to file another bug if you are still facing this issue.
