### ISSUE TITLE
Update to roku TV causes RoMote to not work 

### ISSUE THREAD

**Issue by wjrohret** [wseemann/RoMote#41]
I recently updated to TCL roku Sw ver. 14.1.4 build 7708.

Devices tab/page says it's connected to the tv

None of the remote control buttons work (D-pad, power, volume, etc)

Channels sort of work. I can switch to various streaming channels but not any of the inputs like live tv

RoMote ver 1.0.27

**Comment by YoelFievelBenAvram** [comment]
Confirming the problem but mine doesn't list anything in the channels tab. Otherwise it detects and connects devices but no inputs work.

**Comment by wseemann** [comment]
This isn't an issue with RoMote. Roku disabled third party ECP access in the latest OS update. You need to enable it manually for this app to work: https://support.roku.com/article/217288467

**Comment by wjrohret** [comment]
Yup that fixes the issues for me
