### ISSUE TITLE
Never works - All of the sudden (Past 7 days)

### ISSUE THREAD

**Issue by Siemprepositivo7** [wseemann/RoMote#42]
Nothing happens when press any buttons 🙄 Guess the other developers haven't shared there secrets with this one 😅😂🤣😀

**Comment by Siemprepositivo7** [comment]
Nothing happens when press any buttons 🙄 Guess the other developers haven't shared there secrets with this one 😅😂🤣😀

**Comment by wseemann** [comment]
https://github.com/wseemann/RoMote/issues/41#issuecomment-2544576174
