### ISSUE TITLE
Add casting support

### ISSUE THREAD

**Issue by thirashima** [wseemann/RoMote#8]
Would it be out of scope to add media casting support? The official Roku app does this, but only allows you to cast photos or videos that are on your device. Being able to share a media URL and have your Roku play it would be a super useful feature. There are a lot of paid apps that do this, but an open source solution would be great!

**Comment by wseemann** [comment]
Thanks for the suggestion @thirashima however adding casting support for this application probably won't happen. Apps like YouTube appear to use some sort of DIAL protocol implementation and I can't find an open source implementation to use. Writing one from scratch would take far too much time just to achieve basic casting support. Roku's Android app likely makes use of some internal API to enable casting. Much like private listening, I can't add support for features like this unless Roku makes the APIs available.
